/**
 * Domain categorizer — assigns task categories based on keyword matching.
 * Uses the 10-domain universal taxonomy for routing, analytics, and lens selection.
 */

import type { MeshDomain } from "@randal/core";

/**
 * Default keyword lists for the 10-domain universal taxonomy.
 * Keys are MeshDomain slugs. Values are lowercase keyword arrays.
 */
export const DEFAULT_DOMAIN_KEYWORDS: Record<string, string[]> = {
	"product-engineering": [
		"react",
		"vue",
		"angular",
		"css",
		"html",
		"component",
		"jsx",
		"tsx",
		"styled",
		"sass",
		"less",
		"webpack",
		"vite",
		"dom",
		"browser",
		"button",
		"form",
		"layout",
		"tailwind",
		"next.js",
		"svelte",
		"api",
		"server",
		"endpoint",
		"rest",
		"graphql",
		"middleware",
		"express",
		"hono",
		"fastify",
		"route",
		"handler",
		"controller",
		"service",
		"authentication",
		"authorization",
		"jwt",
		"oauth",
		"websocket",
		"http",
		"cors",
		"sql",
		"query",
		"migration",
		"schema",
		"postgres",
		"mysql",
		"sqlite",
		"prisma",
		"drizzle",
		"mongodb",
		"redis",
		"table",
		"column",
		"foreign key",
		"join",
		"orm",
		"seed",
		"transaction",
		"architecture",
		"refactor",
		"feature",
		"bug",
		"crud",
		"sdk",
		"library",
		"package",
		"build",
		"compile",
		"typescript",
		"python",
		"rust",
		"go",
		"test",
		"spec",
		"jest",
		"vitest",
		"cypress",
		"playwright",
		"coverage",
		"mock",
		"stub",
		"fixture",
		"assertion",
		"e2e",
		"integration test",
		"unit test",
		"snapshot",
	],
	"platform-infrastructure": [
		"docker",
		"kubernetes",
		"ci",
		"cd",
		"deploy",
		"terraform",
		"aws",
		"gcp",
		"azure",
		"nginx",
		"load balancer",
		"ssl",
		"certificate",
		"dns",
		"monitoring",
		"logging",
		"k8s",
		"container",
		"pipeline",
		"github actions",
		"sre",
		"observability",
		"prometheus",
		"grafana",
		"datadog",
		"helm",
		"ansible",
		"pulumi",
		"cloudflare",
		"uptime",
		"incident",
	],
	"security-compliance": [
		"security",
		"vulnerability",
		"cve",
		"audit",
		"compliance",
		"gdpr",
		"hipaa",
		"soc2",
		"penetration",
		"encryption",
		"firewall",
		"access control",
		"rbac",
		"owasp",
		"secret",
		"scan",
	],
	"data-intelligence": [
		"data",
		"analytics",
		"ml",
		"machine learning",
		"model training",
		"dataset",
		"etl",
		"warehouse",
		"bigquery",
		"snowflake",
		"spark",
		"pandas",
		"notebook",
		"dashboard",
		"bi",
		"metrics",
		"reporting",
	],
	"design-experience": [
		"design",
		"ux",
		"ui",
		"figma",
		"accessibility",
		"a11y",
		"i18n",
		"localization",
		"design system",
		"prototype",
		"wireframe",
		"usability",
		"responsive",
		"animation",
		"color",
		"typography",
	],
	"content-communications": [
		"readme",
		"documentation",
		"docs",
		"guide",
		"tutorial",
		"changelog",
		"comment",
		"jsdoc",
		"typedoc",
		"api reference",
		"blog",
		"article",
		"whitepaper",
		"release notes",
		"press",
		"newsletter",
		"copy",
		"style guide",
		"brand",
		"messaging",
		"announcement",
		"marketing",
	],
	"revenue-growth": [
		"sales",
		"revenue",
		"pricing",
		"conversion",
		"funnel",
		"lead",
		"deal",
		"quota",
		"gtm",
		"go to market",
		"partner",
		"channel",
		"acquisition",
		"growth",
	],
	"customer-operations": [
		"support",
		"ticket",
		"customer",
		"onboarding",
		"churn",
		"nps",
		"satisfaction",
		"helpdesk",
		"zendesk",
		"intercom",
		"escalation",
		"sla",
		"success",
	],
	"strategy-finance": [
		"roadmap",
		"okr",
		"kpi",
		"budget",
		"forecast",
		"plan",
		"strategy",
		"prioritize",
		"backlog",
		"sprint",
		"finance",
		"invoice",
		"accounting",
		"headcount",
		"burn rate",
	],
	"legal-governance": [
		"contract",
		"legal",
		"policy",
		"terms",
		"license",
		"ip",
		"patent",
		"trademark",
		"nda",
		"regulatory",
		"litigation",
		"jurisdiction",
		"counsel",
		"governance",
	],
};

/**
 * Categorize a prompt text into domains based on keyword matching.
 * Returns all matching domains, sorted by match count (highest first).
 */
export function categorizePrompt(
	prompt: string,
	domainKeywords: Record<string, string[]> = DEFAULT_DOMAIN_KEYWORDS,
): string[] {
	const lower = prompt.toLowerCase();
	const scores: { domain: string; count: number }[] = [];

	for (const [domain, keywords] of Object.entries(domainKeywords)) {
		let count = 0;
		for (const keyword of keywords) {
			if (lower.includes(keyword.toLowerCase())) {
				count++;
			}
		}
		if (count > 0) {
			scores.push({ domain, count });
		}
	}

	// Sort by count descending
	scores.sort((a, b) => b.count - a.count);

	return scores.map((s) => s.domain);
}

/**
 * Get the primary domain for a prompt.
 * Returns "general" if no specific domain matched.
 */
export function getPrimaryDomain(
	prompt: string,
	domainKeywords: Record<string, string[]> = DEFAULT_DOMAIN_KEYWORDS,
): string {
	const domains = categorizePrompt(prompt, domainKeywords);
	return domains[0] ?? "general";
}
